language: java
jdk: openjdk8

branches:
  only: [ "master" ]

git:
  depth: 3

addons:
  apt:
    packages: &common_linux_packages
      - cmake
      - automake
      - nasm
      - build-essential
      - autoconf
      - libtool
      - libglib2.0-dev
      - libexpat1-dev
      - gtk-doc-tools
      - gobject-introspection
      - zlib1g-dev

matrix:
  fast_finish: true

  include:
      - name: "JVips Linux target"
        os: linux
        sudo: required
        dist: xenial
        compiler: gcc
        package:
          - *common_linux_packages
        script:
          - ./build.sh --without-w64

  include:
      - name: "JVips minimal Linux target"
        os: linux
        sudo: required
        dist: xenial
        compiler: gcc
        package:
          - *common_linux_packages
        before_script:
          - export LD_LIBRARY_PATH=./build/linux/inst/lib/
        script:
          - ./build.sh --minimal --without-w64