/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_criteo_vips_Max1Result */

#ifndef _Included_com_criteo_vips_Max1Result
#define _Included_com_criteo_vips_Max1Result
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_criteo_vips_Max1Result
 * Method:    initMax1ResultFieldIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_Max1Result_initMax1ResultFieldIDs
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
