/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_criteo_vips_Vips */

#ifndef _Included_com_criteo_vips_Vips
#define _Included_com_criteo_vips_Vips
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_criteo_vips_Vips
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_Vips_init
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
