/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_criteo_vips_VipsContext */

#ifndef _Included_com_criteo_vips_VipsContext
#define _Included_com_criteo_vips_VipsContext
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_criteo_vips_VipsContext
 * Method:    setLeak
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_VipsContext_setLeak
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     com_criteo_vips_VipsContext
 * Method:    setConcurrency
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_VipsContext_setConcurrency
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_criteo_vips_VipsContext
 * Method:    getConcurrency
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_criteo_vips_VipsContext_getConcurrency
  (JNIEnv *, jclass);

/*
 * Class:     com_criteo_vips_VipsContext
 * Method:    setMaxCache
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_VipsContext_setMaxCache
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_criteo_vips_VipsContext
 * Method:    getMaxCache
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_criteo_vips_VipsContext_getMaxCache
  (JNIEnv *, jclass);

/*
 * Class:     com_criteo_vips_VipsContext
 * Method:    setMaxCacheMem
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_VipsContext_setMaxCacheMem
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_criteo_vips_VipsContext
 * Method:    getMaxCacheMem
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_criteo_vips_VipsContext_getMaxCacheMem
  (JNIEnv *, jclass);

/*
 * Class:     com_criteo_vips_VipsContext
 * Method:    shutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_VipsContext_shutdown
  (JNIEnv *, jclass);

/*
 * Class:     com_criteo_vips_VipsContext
 * Method:    setBlockUntrusted
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_VipsContext_setBlockUntrusted
  (JNIEnv *, jclass, jboolean);

#ifdef __cplusplus
}
#endif
#endif
