/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_criteo_vips_VipsEnumTest */

#ifndef _Included_com_criteo_vips_VipsEnumTest
#define _Included_com_criteo_vips_VipsEnumTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_criteo_vips_VipsEnumTest
 * Method:    TestNativeEnums
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_VipsEnumTest_TestNativeEnums
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
